services:

  capitegory_backend:
    container_name: capitegory_back
    image: ${DOCKER_REGISTRY-}capitegorybackend
    build:
      context: .
      dockerfile: CAPItegory_backend/Dockerfile

  database_sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database_sql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
