services:

  capitegory_backend:
    container_name: capitegory-back
    image: ${DOCKER_REGISTRY-}capitegorybackend
    build:
      context: .
      dockerfile: CAPItegory_backend/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}

  capitegory-sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: capitegory-sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}

