// <auto-generated />
using System;
using CAPItegory_backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAPItegory_backend.Migrations
{
    [DbContext(typeof(CapitegoryContext))]
    partial class CapitegoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAPItegory_backend.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3bcd498-276a-4cb7-ad45-d09360c23789"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7393),
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("3995002e-99f5-4a11-922d-09b82b613ca2"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7435),
                            Name = "Programming",
                            ParentId = new Guid("a3bcd498-276a-4cb7-ad45-d09360c23789")
                        },
                        new
                        {
                            Id = new Guid("221933d9-2175-4ce6-ae18-1cc6915f9e5c"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7438),
                            Name = "Languages",
                            ParentId = new Guid("3995002e-99f5-4a11-922d-09b82b613ca2")
                        },
                        new
                        {
                            Id = new Guid("eb97e739-0923-4574-9b5d-98357af2ca7f"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7443),
                            Name = "C#",
                            ParentId = new Guid("221933d9-2175-4ce6-ae18-1cc6915f9e5c")
                        },
                        new
                        {
                            Id = new Guid("37efe3ed-3f47-4105-80b3-d8ef986a4fcc"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7446),
                            Name = "JavaScript",
                            ParentId = new Guid("221933d9-2175-4ce6-ae18-1cc6915f9e5c")
                        },
                        new
                        {
                            Id = new Guid("480d9706-14d7-4ac3-bf82-49a80c1c7a80"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7448),
                            Name = "Frameworks",
                            ParentId = new Guid("3995002e-99f5-4a11-922d-09b82b613ca2")
                        },
                        new
                        {
                            Id = new Guid("016cad32-67ab-45e3-82ad-9305f19c209c"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7451),
                            Name = ".NET",
                            ParentId = new Guid("480d9706-14d7-4ac3-bf82-49a80c1c7a80")
                        },
                        new
                        {
                            Id = new Guid("325bad03-9ae7-4c42-ac4b-647ed60a20f9"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7454),
                            Name = "Node.js",
                            ParentId = new Guid("480d9706-14d7-4ac3-bf82-49a80c1c7a80")
                        },
                        new
                        {
                            Id = new Guid("053e35a8-e95f-40b8-8fc3-867b4d576499"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7456),
                            Name = "Databases",
                            ParentId = new Guid("a3bcd498-276a-4cb7-ad45-d09360c23789")
                        },
                        new
                        {
                            Id = new Guid("a811967d-97e0-4fd3-bea3-98766ea2fc65"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7458),
                            Name = "SQL",
                            ParentId = new Guid("053e35a8-e95f-40b8-8fc3-867b4d576499")
                        },
                        new
                        {
                            Id = new Guid("2ab35904-af7c-4e47-85db-27b89bedc3cb"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7461),
                            Name = "MySQL",
                            ParentId = new Guid("a811967d-97e0-4fd3-bea3-98766ea2fc65")
                        },
                        new
                        {
                            Id = new Guid("6df438e1-2abe-40b0-be6d-14e6e08b0fa6"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7464),
                            Name = "PostgreSQL",
                            ParentId = new Guid("a811967d-97e0-4fd3-bea3-98766ea2fc65")
                        },
                        new
                        {
                            Id = new Guid("7f3377ec-aaf2-44c9-8954-35192f41d9d2"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7466),
                            Name = "NoSQL",
                            ParentId = new Guid("053e35a8-e95f-40b8-8fc3-867b4d576499")
                        },
                        new
                        {
                            Id = new Guid("e17be77b-62d9-4610-9e51-9a9407d4ef3f"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7469),
                            Name = "MongoDB",
                            ParentId = new Guid("7f3377ec-aaf2-44c9-8954-35192f41d9d2")
                        },
                        new
                        {
                            Id = new Guid("f79a9ab7-5e5c-4028-ae14-70ae238e3e66"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7472),
                            Name = "Cassandra",
                            ParentId = new Guid("7f3377ec-aaf2-44c9-8954-35192f41d9d2")
                        },
                        new
                        {
                            Id = new Guid("7c3977c2-522f-4d45-b79d-b68c3f9671d3"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7475),
                            Name = "DevOps",
                            ParentId = new Guid("a3bcd498-276a-4cb7-ad45-d09360c23789")
                        },
                        new
                        {
                            Id = new Guid("064a0a38-9b3b-4776-b854-0297b68acac8"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7477),
                            Name = "CI/CD",
                            ParentId = new Guid("7c3977c2-522f-4d45-b79d-b68c3f9671d3")
                        },
                        new
                        {
                            Id = new Guid("57690f2d-42c2-4bd5-a46b-c36d67471a53"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7482),
                            Name = "Jenkins",
                            ParentId = new Guid("064a0a38-9b3b-4776-b854-0297b68acac8")
                        },
                        new
                        {
                            Id = new Guid("9664372c-8b34-46e2-b200-b5b7ac3f85d2"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7485),
                            Name = "GitLab CI",
                            ParentId = new Guid("064a0a38-9b3b-4776-b854-0297b68acac8")
                        },
                        new
                        {
                            Id = new Guid("5d6a4a1a-3c54-41f6-a132-2e6b05cd583f"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7488),
                            Name = "Docker",
                            ParentId = new Guid("7c3977c2-522f-4d45-b79d-b68c3f9671d3")
                        },
                        new
                        {
                            Id = new Guid("9c672a70-200e-4ad9-a4fb-2e5b44e3e4ba"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7490),
                            Name = "Kubernetes",
                            ParentId = new Guid("7c3977c2-522f-4d45-b79d-b68c3f9671d3")
                        },
                        new
                        {
                            Id = new Guid("2cee80b2-6399-4302-acb5-7613af8daa95"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7492),
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("3d37b1ba-c612-4c30-bdd4-f352361e78f9"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7495),
                            Name = "Painting",
                            ParentId = new Guid("2cee80b2-6399-4302-acb5-7613af8daa95")
                        },
                        new
                        {
                            Id = new Guid("df1ece28-8286-48f1-bd7d-7c3a60ac0ebc"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7498),
                            Name = "Sculpture",
                            ParentId = new Guid("2cee80b2-6399-4302-acb5-7613af8daa95")
                        },
                        new
                        {
                            Id = new Guid("9e676cf0-d2d4-4b20-92b4-ed617a811cde"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7500),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("478c4296-4e07-4f37-a594-2f6d7973b74f"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7503),
                            Name = "Classical",
                            ParentId = new Guid("9e676cf0-d2d4-4b20-92b4-ed617a811cde")
                        },
                        new
                        {
                            Id = new Guid("4f7f9971-77ed-4d89-8d1c-8939953d5cb6"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7506),
                            Name = "Rock",
                            ParentId = new Guid("9e676cf0-d2d4-4b20-92b4-ed617a811cde")
                        },
                        new
                        {
                            Id = new Guid("4912e1ed-dc26-4f4f-a11c-8650cf744e79"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7508),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("de0ec14b-c82a-45ae-b577-5fbf85111464"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7513),
                            Name = "Football",
                            ParentId = new Guid("4912e1ed-dc26-4f4f-a11c-8650cf744e79")
                        },
                        new
                        {
                            Id = new Guid("883e1c5d-0c21-49bb-85a3-7e0da663550b"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7515),
                            Name = "Basketball",
                            ParentId = new Guid("4912e1ed-dc26-4f4f-a11c-8650cf744e79")
                        },
                        new
                        {
                            Id = new Guid("575b513b-86cc-4b64-b66a-64256098f778"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7518),
                            Name = "Literature"
                        },
                        new
                        {
                            Id = new Guid("19f749e6-64ea-43ab-8e0b-3be6f338b7fc"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7520),
                            Name = "Fiction",
                            ParentId = new Guid("575b513b-86cc-4b64-b66a-64256098f778")
                        },
                        new
                        {
                            Id = new Guid("6225d0af-5c63-4fde-9eb8-4b353130f878"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7523),
                            Name = "Non-Fiction",
                            ParentId = new Guid("575b513b-86cc-4b64-b66a-64256098f778")
                        },
                        new
                        {
                            Id = new Guid("9354b27c-fc41-4160-a468-8e26777e2287"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7525),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("9116495b-687a-4926-affd-b4f20f22efa3"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7528),
                            Name = "Ancient",
                            ParentId = new Guid("9354b27c-fc41-4160-a468-8e26777e2287")
                        },
                        new
                        {
                            Id = new Guid("290a1e66-f452-4465-bb06-9e6069a94998"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7555),
                            Name = "Modern",
                            ParentId = new Guid("9354b27c-fc41-4160-a468-8e26777e2287")
                        },
                        new
                        {
                            Id = new Guid("517f999d-5016-436b-b637-e46f866ff06b"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7558),
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("7f1303b0-4292-42e4-bcfb-9345884669a3"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7560),
                            Name = "Physics",
                            ParentId = new Guid("517f999d-5016-436b-b637-e46f866ff06b")
                        },
                        new
                        {
                            Id = new Guid("a2a682d1-829f-4f8d-8495-02e43fe1e0c1"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7562),
                            Name = "Chemistry",
                            ParentId = new Guid("517f999d-5016-436b-b637-e46f866ff06b")
                        },
                        new
                        {
                            Id = new Guid("f341e088-7c8f-40c1-9e3d-fe1e93e58503"),
                            CreationDate = new DateTime(2024, 11, 17, 13, 26, 35, 136, DateTimeKind.Local).AddTicks(7564),
                            Name = "Biology",
                            ParentId = new Guid("517f999d-5016-436b-b637-e46f866ff06b")
                        });
                });

            modelBuilder.Entity("CAPItegory_backend.Models.Category", b =>
                {
                    b.HasOne("CAPItegory_backend.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CAPItegory_backend.Models.Category", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
